backend:
  name: github
  repo: 5march2008/portfolio
  branch: main
  base_url: https://decap-oauth-hubaib.vercel.app

media_folder: "assets/certifications"
public_folder: "/assets/certifications"

collections:
  - name: "certificates"
    label: "Certificates"
    files:
      - file: "content/certificates.json"
        name: "certificates"
        label: "Certificates List"
        format: "json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Link (optional)", name: "link", widget: "string", required: false}
